import React, { useRef } from "react";

function ScrollBar() {
  const container1Ref = useRef(null);
  const container2Ref = useRef(null);

  const handleScroll1 = () => {
    container2Ref.current.scrollTop = container1Ref.current.scrollTop;
  };

  const handleScroll2 = () => {
    container1Ref.current.scrollTop = container2Ref.current.scrollTop;
  };

  return (
    <>
    <div>
      <div
        className="container"
        ref={container1Ref}
        onScroll={handleScroll1}
        style={{height:'20vh', overflowY:'scroll'}}
      >
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempus lectus eget ex fringilla, ac laoreet mauris hendrerit. Praesent eu mauris vel massa aliquet sodales ac vel velit. Sed non dui eu purus feugiat eleifend. Nulla vel purus sit amet magna auctor tristique. Nullam sit amet sapien a massa mollis consequat. Integer ut mi vel massa finibus ultricies. Fusce dapibus quam vel tellus feugiat, vel suscipit arcu dapibus. Sed rhoncus, sem in fermentum maximus, ipsum dolor faucibus orci, a iaculis quam purus eu risus. Mauris efficitur elit vel sapien bibendum, id ultricies eros consequat. Sed nec mauris eget ante finibus euismod. Suspendisse a dolor vitae massa gravida cursus. Sed sed mauris dolor. Donec tristique semper est, at finibus tellus lobortis eu. Nam eget ullamcorper turpis, quis interdum felis.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempus lectus eget ex fringilla, ac laoreet mauris hendrerit. Praesent eu mauris vel massa aliquet sodales ac vel velit. Sed non dui eu purus feugiat eleifend. Nulla vel purus sit amet magna auctor tristique. Nullam sit amet sapien a massa mollis consequat. Integer ut mi vel massa finibus ultricies. Fusce dapibus quam vel tellus feugiat, vel suscipit arcu dapibus. Sed rhoncus, sem in fermentum maximus, ipsum dolor faucibus orci, a iaculis quam purus eu risus. Mauris efficitur elit vel sapien bibendum, id ultricies eros consequat. Sed nec mauris eget ante finibus euismod. Suspendisse a dolor vitae massa gravida cursus. Sed sed mauris dolor. Donec tristique semper est, at finibus tellus lobortis eu. Nam eget ullamcorper turpis, quis interdum felis.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempus lectus eget ex fringilla, ac laoreet mauris hendrerit. Praesent eu mauris vel massa aliquet sodales ac vel velit. Sed non dui eu purus feugiat eleifend. Nulla vel purus sit amet magna auctor tristique. Nullam sit amet sapien a massa mollis consequat. Integer ut mi vel massa finibus ultricies. Fusce dapibus quam vel tellus feugiat, vel suscipit arcu dapibus. Sed rhoncus, sem in fermentum maximus, ipsum dolor faucibus orci, a iaculis quam purus eu risus. Mauris efficitur elit vel sapien bibendum, id ultricies eros consequat. Sed nec mauris eget ante finibus euismod. Suspendisse a dolor vitae massa gravida cursus. Sed sed mauris dolor. Donec tristique semper est, at finibus tellus lobortis eu. Nam eget ullamcorper turpis, quis interdum felis.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempus lectus eget ex fringilla, ac laoreet mauris hendrerit. Praesent eu mauris vel massa aliquet sodales ac vel velit. Sed non dui eu purus feugiat eleifend. Nulla vel purus sit amet magna auctor tristique. Nullam sit amet sapien a massa mollis consequat. Integer ut mi vel massa finibus ultricies. Fusce dapibus quam vel tellus feugiat, vel suscipit arcu dapibus. Sed rhoncus, sem in fermentum maximus, ipsum dolor faucibus orci, a iaculis quam purus eu risus. Mauris efficitur elit vel sapien bibendum, id ultricies eros consequat. Sed nec mauris eget ante finibus euismod. Suspendisse a dolor vitae massa gravida cursus. Sed sed mauris dolor. Donec tristique semper est, at finibus tellus lobortis eu. Nam eget ullamcorper turpis, quis interdum felis.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempus lectus eget ex fringilla, ac laoreet mauris hendrerit. Praesent eu mauris vel massa aliquet sodales ac vel velit. Sed non dui eu purus feugiat eleifend. Nulla vel purus sit amet magna auctor tristique. Nullam sit amet sapien a massa mollis consequat. Integer ut mi vel massa finibus ultricies. Fusce dapibus quam vel tellus feugiat, vel suscipit arcu dapibus. Sed rhoncus, sem in fermentum maximus, ipsum dolor faucibus orci, a iaculis quam purus eu risus. Mauris efficitur elit vel sapien bibendum, id ultricies eros consequat. Sed nec mauris eget ante finibus euismod. Suspendisse a dolor vitae massa gravida cursus. Sed sed mauris dolor. Donec tristique semper est, at finibus tellus lobortis eu. Nam eget ullamcorper turpis, quis interdum felis.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempus lectus eget ex fringilla, ac laoreet mauris hendrerit. Praesent eu mauris vel massa aliquet sodales ac vel velit. Sed non dui eu purus feugiat eleifend. Nulla vel purus sit amet magna auctor tristique. Nullam sit amet sapien a massa mollis consequat. Integer ut mi vel massa finibus ultricies. Fusce dapibus quam vel tellus feugiat, vel suscipit arcu dapibus. Sed rhoncus, sem in fermentum maximus, ipsum dolor faucibus orci, a iaculis quam purus eu risus. Mauris efficitur elit vel sapien bibendum, id ultricies eros consequat. Sed nec mauris eget ante finibus euismod. Suspendisse a dolor vitae massa gravida cursus. Sed sed mauris dolor. Donec tristique semper est, at finibus tellus lobortis eu. Nam eget ullamcorper turpis, quis interdum felis.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempus lectus eget ex fringilla, ac laoreet mauris hendrerit. Praesent eu mauris vel massa aliquet sodales ac vel velit. Sed non dui eu purus feugiat eleifend. Nulla vel purus sit amet magna auctor tristique. Nullam sit amet sapien a massa mollis consequat. Integer ut mi vel massa finibus ultricies. Fusce dapibus quam vel tellus feugiat, vel suscipit arcu dapibus. Sed rhoncus, sem in fermentum maximus, ipsum dolor faucibus orci, a iaculis quam purus eu risus. Mauris efficitur elit vel sapien bibendum, id ultricies eros consequat. Sed nec mauris eget ante finibus euismod. Suspendisse a dolor vitae massa gravida cursus. Sed sed mauris dolor. Donec tristique semper est, at finibus tellus lobortis eu. Nam eget ullamcorper turpis, quis interdum felis.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempus lectus eget ex fringilla, ac laoreet mauris hendrerit. Praesent eu mauris vel massa aliquet sodales ac vel velit. Sed non dui eu purus feugiat eleifend. Nulla vel purus sit amet magna auctor tristique. Nullam sit amet sapien a massa mollis consequat. Integer ut mi vel massa finibus ultricies. Fusce dapibus quam vel tellus feugiat, vel suscipit arcu dapibus. Sed rhoncus, sem in fermentum maximus, ipsum dolor faucibus orci, a iaculis quam purus eu risus. Mauris efficitur elit vel sapien bibendum, id ultricies eros consequat. Sed nec mauris eget ante finibus euismod. Suspendisse a dolor vitae massa gravida cursus. Sed sed mauris dolor. Donec tristique semper est, at finibus tellus lobortis eu. Nam eget ullamcorper turpis, quis interdum felis.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempus lectus eget ex fringilla, ac laoreet mauris hendrerit. Praesent eu mauris vel massa aliquet sodales ac vel velit. Sed non dui eu purus feugiat eleifend. Nulla vel purus sit amet magna auctor tristique. Nullam sit amet sapien a massa mollis consequat. Integer ut mi vel massa finibus ultricies. Fusce dapibus quam vel tellus feugiat, vel suscipit arcu dapibus. Sed rhoncus, sem in fermentum maximus, ipsum dolor faucibus orci, a iaculis quam purus eu risus. Mauris efficitur elit vel sapien bibendum, id ultricies eros consequat. Sed nec mauris eget ante finibus euismod. Suspendisse a dolor vitae massa gravida cursus. Sed sed mauris dolor. Donec tristique semper est, at finibus tellus lobortis eu. Nam eget ullamcorper turpis, quis interdum felis.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempus lectus eget ex fringilla, ac laoreet mauris hendrerit. Praesent eu mauris vel massa aliquet sodales ac vel velit. Sed non dui eu purus feugiat eleifend. Nulla vel purus sit amet magna auctor tristique. Nullam sit amet sapien a massa mollis consequat. Integer ut mi vel massa finibus ultricies. Fusce dapibus quam vel tellus feugiat, vel suscipit arcu dapibus. Sed rhoncus, sem in fermentum maximus, ipsum dolor faucibus orci, a iaculis quam purus eu risus. Mauris efficitur elit vel sapien bibendum, id ultricies eros consequat. Sed nec mauris eget ante finibus euismod. Suspendisse a dolor vitae massa gravida cursus. Sed sed mauris dolor. Donec tristique semper est, at finibus tellus lobortis eu. Nam eget ullamcorper turpis, quis interdum felis.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempus lectus eget ex fringilla, ac laoreet mauris hendrerit. Praesent eu mauris vel massa aliquet sodales ac vel velit. Sed non dui eu purus feugiat eleifend. Nulla vel purus sit amet magna auctor tristique. Nullam sit amet sapien a massa mollis consequat. Integer ut mi vel massa finibus ultricies. Fusce dapibus quam vel tellus feugiat, vel suscipit arcu dapibus. Sed rhoncus, sem in fermentum maximus, ipsum dolor faucibus orci, a iaculis quam purus eu risus. Mauris efficitur elit vel sapien bibendum, id ultricies eros consequat. Sed nec mauris eget ante finibus euismod. Suspendisse a dolor vitae massa gravida cursus. Sed sed mauris dolor. Donec tristique semper est, at finibus tellus lobortis eu. Nam eget ullamcorper turpis, quis interdum felis.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempus lectus eget ex fringilla, ac laoreet mauris hendrerit. Praesent eu mauris vel massa aliquet sodales ac vel velit. Sed non dui eu purus feugiat eleifend. Nulla vel purus sit amet magna auctor tristique. Nullam sit amet sapien a massa mollis consequat. Integer ut mi vel massa finibus ultricies. Fusce dapibus quam vel tellus feugiat, vel suscipit arcu dapibus. Sed rhoncus, sem in fermentum maximus, ipsum dolor faucibus orci, a iaculis quam purus eu risus. Mauris efficitur elit vel sapien bibendum, id ultricies eros consequat. Sed nec mauris eget ante finibus euismod. Suspendisse a dolor vitae massa gravida cursus. Sed sed mauris dolor. Donec tristique semper est, at finibus tellus lobortis eu. Nam eget ullamcorper turpis, quis interdum felis.
      </div>
      <div
        className="container"
        ref={container2Ref}
        onScroll={handleScroll2}
        style={{height:'20vh', overflowY:'scroll'}}
      >
         Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempus lectus eget ex fringilla, ac laoreet mauris hendrerit. Praesent eu mauris vel massa aliquet sodales ac vel velit. Sed non dui eu purus feugiat eleifend. Nulla vel purus sit amet magna auctor tristique. Nullam sit amet sapien a massa mollis consequat. Integer ut mi vel massa finibus ultricies. Fusce dapibus quam vel tellus feugiat, vel suscipit arcu dapibus. Sed rhoncus, sem in fermentum maximus, ipsum dolor faucibus orci, a iaculis quam purus eu risus. Mauris efficitur elit vel sapien bibendum, id ultricies eros consequat. Sed nec mauris eget ante finibus euismod. Suspendisse a dolor vitae massa gravida cursus. Sed sed mauris dolor. Donec tristique semper est, at finibus tellus lobortis eu. Nam eget ullamcorper turpis, quis interdum felis.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempus lectus eget ex fringilla, ac laoreet mauris hendrerit. Praesent eu mauris vel massa aliquet sodales ac vel velit. Sed non dui eu purus feugiat eleifend. Nulla vel purus sit amet magna auctor tristique. Nullam sit amet sapien a massa mollis consequat. Integer ut mi vel massa finibus ultricies. Fusce dapibus quam vel tellus feugiat, vel suscipit arcu dapibus. Sed rhoncus, sem in fermentum maximus, ipsum dolor faucibus orci, a iaculis quam purus eu risus. Mauris efficitur elit vel sapien bibendum, id ultricies eros consequat. Sed nec mauris eget ante finibus euismod. Suspendisse a dolor vitae massa gravida cursus. Sed sed mauris dolor. Donec tristique semper est, at finibus tellus lobortis eu. Nam eget ullamcorper turpis, quis interdum felis.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempus lectus eget ex fringilla, ac laoreet mauris hendrerit. Praesent eu mauris vel massa aliquet sodales ac vel velit. Sed non dui eu purus feugiat eleifend. Nulla vel purus sit amet magna auctor tristique. Nullam sit amet sapien a massa mollis consequat. Integer ut mi vel massa finibus ultricies. Fusce dapibus quam vel tellus feugiat, vel suscipit arcu dapibus. Sed rhoncus, sem in fermentum maximus, ipsum dolor faucibus orci, a iaculis quam purus eu risus. Mauris efficitur elit vel sapien bibendum, id ultricies eros consequat. Sed nec mauris eget ante finibus euismod. Suspendisse a dolor vitae massa gravida cursus. Sed sed mauris dolor. Donec tristique semper est, at finibus tellus lobortis eu. Nam eget ullamcorper turpis, quis interdum felis.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempus lectus eget ex fringilla, ac laoreet mauris hendrerit. Praesent eu mauris vel massa aliquet sodales ac vel velit. Sed non dui eu purus feugiat eleifend. Nulla vel purus sit amet magna auctor tristique. Nullam sit amet sapien a massa mollis consequat. Integer ut mi vel massa finibus ultricies. Fusce dapibus quam vel tellus feugiat, vel suscipit arcu dapibus. Sed rhoncus, sem in fermentum maximus, ipsum dolor faucibus orci, a iaculis quam purus eu risus. Mauris efficitur elit vel sapien bibendum, id ultricies eros consequat. Sed nec mauris eget ante finibus euismod. Suspendisse a dolor vitae massa gravida cursus. Sed sed mauris dolor. Donec tristique semper est, at finibus tellus lobortis eu. Nam eget ullamcorper turpis, quis interdum felis.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempus lectus eget ex fringilla, ac laoreet mauris hendrerit. Praesent eu mauris vel massa aliquet sodales ac vel velit. Sed non dui eu purus feugiat eleifend. Nulla vel purus sit amet magna auctor tristique. Nullam sit amet sapien a massa mollis consequat. Integer ut mi vel massa finibus ultricies. Fusce dapibus quam vel tellus feugiat, vel suscipit arcu dapibus. Sed rhoncus, sem in fermentum maximus, ipsum dolor faucibus orci, a iaculis quam purus eu risus. Mauris efficitur elit vel sapien bibendum, id ultricies eros consequat. Sed nec mauris eget ante finibus euismod. Suspendisse a dolor vitae massa gravida cursus. Sed sed mauris dolor. Donec tristique semper est, at finibus tellus lobortis eu. Nam eget ullamcorper turpis, quis interdum felis.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempus lectus eget ex fringilla, ac laoreet mauris hendrerit. Praesent eu mauris vel massa aliquet sodales ac vel velit. Sed non dui eu purus feugiat eleifend. Nulla vel purus sit amet magna auctor tristique. Nullam sit amet sapien a massa mollis consequat. Integer ut mi vel massa finibus ultricies. Fusce dapibus quam vel tellus feugiat, vel suscipit arcu dapibus. Sed rhoncus, sem in fermentum maximus, ipsum dolor faucibus orci, a iaculis quam purus eu risus. Mauris efficitur elit vel sapien bibendum, id ultricies eros consequat. Sed nec mauris eget ante finibus euismod. Suspendisse a dolor vitae massa gravida cursus. Sed sed mauris dolor. Donec tristique semper est, at finibus tellus lobortis eu. Nam eget ullamcorper turpis, quis interdum felis.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempus lectus eget ex fringilla, ac laoreet mauris hendrerit. Praesent eu mauris vel massa aliquet sodales ac vel velit. Sed non dui eu purus feugiat eleifend. Nulla vel purus sit amet magna auctor tristique. Nullam sit amet sapien a massa mollis consequat. Integer ut mi vel massa finibus ultricies. Fusce dapibus quam vel tellus feugiat, vel suscipit arcu dapibus. Sed rhoncus, sem in fermentum maximus, ipsum dolor faucibus orci, a iaculis quam purus eu risus. Mauris efficitur elit vel sapien bibendum, id ultricies eros consequat. Sed nec mauris eget ante finibus euismod. Suspendisse a dolor vitae massa gravida cursus. Sed sed mauris dolor. Donec tristique semper est, at finibus tellus lobortis eu. Nam eget ullamcorper turpis, quis interdum felis.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempus lectus eget ex fringilla, ac laoreet mauris hendrerit. Praesent eu mauris vel massa aliquet sodales ac vel velit. Sed non dui eu purus feugiat eleifend. Nulla vel purus sit amet magna auctor tristique. Nullam sit amet sapien a massa mollis consequat. Integer ut mi vel massa finibus ultricies. Fusce dapibus quam vel tellus feugiat, vel suscipit arcu dapibus. Sed rhoncus, sem in fermentum maximus, ipsum dolor faucibus orci, a iaculis quam purus eu risus. Mauris efficitur elit vel sapien bibendum, id ultricies eros consequat. Sed nec mauris eget ante finibus euismod. Suspendisse a dolor vitae massa gravida cursus. Sed sed mauris dolor. Donec tristique semper est, at finibus tellus lobortis eu. Nam eget ullamcorper turpis, quis interdum felis.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempus lectus eget ex fringilla, ac laoreet mauris hendrerit. Praesent eu mauris vel massa aliquet sodales ac vel velit. Sed non dui eu purus feugiat eleifend. Nulla vel purus sit amet magna auctor tristique. Nullam sit amet sapien a massa mollis consequat. Integer ut mi vel massa finibus ultricies. Fusce dapibus quam vel tellus feugiat, vel suscipit arcu dapibus. Sed rhoncus, sem in fermentum maximus, ipsum dolor faucibus orci, a iaculis quam purus eu risus. Mauris efficitur elit vel sapien bibendum, id ultricies eros consequat. Sed nec mauris eget ante finibus euismod. Suspendisse a dolor vitae massa gravida cursus. Sed sed mauris dolor. Donec tristique semper est, at finibus tellus lobortis eu. Nam eget ullamcorper turpis, quis interdum felis.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempus lectus eget ex fringilla, ac laoreet mauris hendrerit. Praesent eu mauris vel massa aliquet sodales ac vel velit. Sed non dui eu purus feugiat eleifend. Nulla vel purus sit amet magna auctor tristique. Nullam sit amet sapien a massa mollis consequat. Integer ut mi vel massa finibus ultricies. Fusce dapibus quam vel tellus feugiat, vel suscipit arcu dapibus. Sed rhoncus, sem in fermentum maximus, ipsum dolor faucibus orci, a iaculis quam purus eu risus. Mauris efficitur elit vel sapien bibendum, id ultricies eros consequat. Sed nec mauris eget ante finibus euismod. Suspendisse a dolor vitae massa gravida cursus. Sed sed mauris dolor. Donec tristique semper est, at finibus tellus lobortis eu. Nam eget ullamcorper turpis, quis interdum felis.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempus lectus eget ex fringilla, ac laoreet mauris hendrerit. Praesent eu mauris vel massa aliquet sodales ac vel velit. Sed non dui eu purus feugiat eleifend. Nulla vel purus sit amet magna auctor tristique. Nullam sit amet sapien a massa mollis consequat. Integer ut mi vel massa finibus ultricies. Fusce dapibus quam vel tellus feugiat, vel suscipit arcu dapibus. Sed rhoncus, sem in fermentum maximus, ipsum dolor faucibus orci, a iaculis quam purus eu risus. Mauris efficitur elit vel sapien bibendum, id ultricies eros consequat. Sed nec mauris eget ante finibus euismod. Suspendisse a dolor vitae massa gravida cursus. Sed sed mauris dolor. Donec tristique semper est, at finibus tellus lobortis eu. Nam eget ullamcorper turpis, quis interdum felis.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempus lectus eget ex fringilla, ac laoreet mauris hendrerit. Praesent eu mauris vel massa aliquet sodales ac vel velit. Sed non dui eu purus feugiat eleifend. Nulla vel purus sit amet magna auctor tristique. Nullam sit amet sapien a massa mollis consequat. Integer ut mi vel massa finibus ultricies. Fusce dapibus quam vel tellus feugiat, vel suscipit arcu dapibus. Sed rhoncus, sem in fermentum maximus, ipsum dolor faucibus orci, a iaculis quam purus eu risus. Mauris efficitur elit vel sapien bibendum, id ultricies eros consequat. Sed nec mauris eget ante finibus euismod. Suspendisse a dolor vitae massa gravida cursus. Sed sed mauris dolor. Donec tristique semper est, at finibus tellus lobortis eu. Nam eget ullamcorper turpis, quis interdum felis.
      </div>

    </div>
    </>
  );
}

export default ScrollBar;
